### ISSUE TITLE
Error downloading object: data/additional_seed.json

### ISSUE THREAD

**Issue by chao-peng** [qishenghu/CodeInstruct#1]
It looks like larger fils are prohibited from cloning as the repo exceeds the Git LFS quota. Is it possible to publish the dataset to hugging face? Thank you.

Error message:

> Error downloading object: data/additional_seed.json (971e71c): Smudge error: Error downloading data/additional_seed.json (971e71ce61c46d0db2ce171a4874ea73570d7d99a4c0a3eede4adf38dd717418): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by likaixin2000** [comment]
Thank you for letting us know. We will try to fix the LFS issue.

The Huggingface link to the dataset is https://huggingface.co/datasets/happylkx/InstructCoder.

**Comment by qishenghu** [comment]
Please kindly find the dataset in this google drive link.
https://drive.google.com/drive/folders/1_P40wErxgB6PNK2jwVeMdbpTrjXZ3E5v?usp=sharing

**Comment by chao-peng** [comment]
Thank you very much @Happylkx and @qishenghu for the HuggingFace and Google Drive link. Really appreciate it!
