### ISSUE TITLE
How to obtain the EditEval test set?

### ISSUE THREAD

**Issue by allanj** [qishenghu/CodeInstruct#3]
As mentioned in the paper, there are 194 code editing tasks:

__derived from GitHub commit, MBPP and Humaneval__

would you mind pointing me to that

**Comment by likaixin2000** [comment]
Hi allanj, thank you for your interest in our work. We have already pushed a new commit containing the EditEval test set. Please check it out [here](https://github.com/qishenghu/CodeInstruct/blob/main/edit_eval/edit_eval.jsonl). Feel free to reach out to me if you have further questions!

**Comment by allanj** [comment]
Really thanks for the prompt response.
